# Generated by Django 5.0.6 on 2024-05-20 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nik', models.CharField(blank=True, max_length=16, null=True)),
                ('tempat_lahir', models.TextField(blank=True, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=16, null=True)),
                ('no_hp_ortu', models.CharField(blank=True, max_length=16, null=True)),
                ('dusun', models.TextField(blank=True, null=True)),
                ('kelurahan', models.TextField(blank=True, null=True)),
                ('kecamatan', models.TextField(blank=True, null=True)),
                ('kota', models.TextField(blank=True, null=True)),
                ('jenis_kelamin', models.TextField(blank=True, null=True)),
                ('program1', models.TextField(blank=True, null=True)),
                ('program2', models.TextField(blank=True, null=True)),
                ('program3', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pengguna')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. Formulir',
            },
        ),
    ]
