# Generated by Django 5.0.6 on 2024-05-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulir',
            old_name='program1',
            new_name='prog1',
        ),
        migrations.RenameField(
            model_name='formulir',
            old_name='program2',
            new_name='prog2',
        ),
        migrations.RenameField(
            model_name='formulir',
            old_name='program3',
            new_name='prog3',
        ),
        migrations.RemoveField(
            model_name='formulir',
            name='dusun',
        ),
    ]
