# Generated by Django 5.0.6 on 2024-05-31 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0006_pendaftar_delete_pendaftaran_remove_formulir_prog3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulir',
            options={},
        ),
        migrations.RemoveField(
            model_name='formulir',
            name='kota',
        ),
        migrations.RemoveField(
            model_name='formulir',
            name='prog1',
        ),
        migrations.RemoveField(
            model_name='formulir',
            name='prog2',
        ),
        migrations.RemoveField(
            model_name='formulir',
            name='user',
        ),
        migrations.AddField(
            model_name='formulir',
            name='alamat',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulir',
            name='kabupaten',
            field=models.CharField(blank=True, default='Default Kabupaten', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulir',
            name='prodi1',
            field=models.CharField(blank=True, choices=[('S1 - Pendidikan Dokter', 'S1 - Pendidikan Dokter'), ('D4 - Analis Kesehatan', 'D4 - Analis Kesehatan'), ('S1 - Ilmu Kesehatan Masyarakat', 'S1 - Ilmu Kesehatan Masyarakat'), ('S1 - Gizi', 'S1 - Gizi'), ('S1 - PGSD', 'S1 - PGSD'), ('S1 - PGPAUD', 'S1 - PGPAUD'), ('S1 - Pendidikan Bahasa Inggris', 'S1 - Pendidikan Bahasa Inggris'), ('S1 - Akuntansi', 'S1 - Akuntansi'), ('S1 - Manajemen', 'S1 - Manajemen'), ('S1 - Sistem Informasi', 'S1 - Sistem Informasi'), ('S1 - Keperawatan', 'S1 - Keperawatan'), ('D3 - Keperawatan', 'D3 - Keperawatan'), ('D4 - Bidan', 'D4 - Bidan'), ('D3 - Kebidanan', 'D3 - Kebidanan')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formulir',
            name='prodi2',
            field=models.CharField(blank=True, choices=[('S1 - Pendidikan Dokter', 'S1 - Pendidikan Dokter'), ('D4 - Analis Kesehatan', 'D4 - Analis Kesehatan'), ('S1 - Ilmu Kesehatan Masyarakat', 'S1 - Ilmu Kesehatan Masyarakat'), ('S1 - Gizi', 'S1 - Gizi'), ('S1 - PGSD', 'S1 - PGSD'), ('S1 - PGPAUD', 'S1 - PGPAUD'), ('S1 - Pendidikan Bahasa Inggris', 'S1 - Pendidikan Bahasa Inggris'), ('S1 - Akuntansi', 'S1 - Akuntansi'), ('S1 - Manajemen', 'S1 - Manajemen'), ('S1 - Sistem Informasi', 'S1 - Sistem Informasi'), ('S1 - Keperawatan', 'S1 - Keperawatan'), ('D3 - Keperawatan', 'D3 - Keperawatan'), ('D4 - Bidan', 'D4 - Bidan'), ('D3 - Kebidanan', 'D3 - Kebidanan')], default='S1 - Pendidikan Dokter', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formulir',
            name='prodi3',
            field=models.CharField(blank=True, choices=[('S1 - Pendidikan Dokter', 'S1 - Pendidikan Dokter'), ('D4 - Analis Kesehatan', 'D4 - Analis Kesehatan'), ('S1 - Ilmu Kesehatan Masyarakat', 'S1 - Ilmu Kesehatan Masyarakat'), ('S1 - Gizi', 'S1 - Gizi'), ('S1 - PGSD', 'S1 - PGSD'), ('S1 - PGPAUD', 'S1 - PGPAUD'), ('S1 - Pendidikan Bahasa Inggris', 'S1 - Pendidikan Bahasa Inggris'), ('S1 - Akuntansi', 'S1 - Akuntansi'), ('S1 - Manajemen', 'S1 - Manajemen'), ('S1 - Sistem Informasi', 'S1 - Sistem Informasi'), ('S1 - Keperawatan', 'S1 - Keperawatan'), ('D3 - Keperawatan', 'D3 - Keperawatan'), ('D4 - Bidan', 'D4 - Bidan'), ('D3 - Kebidanan', 'D3 - Kebidanan')], default='S1 - Pendidikan Dokter', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='user',
            field=models.OneToOneField(default=-2002, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulir',
            name='foto',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='formulir',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formulir',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formulir',
            name='kelurahan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formulir',
            name='nama',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formulir',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='formulir',
            name='no_hp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='formulir',
            name='no_hp_ortu',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='formulir',
            name='tanggal_lahir',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='formulir',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='umur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
