# Generated by Django 5.0.6 on 2024-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0007_alter_formulir_options_remove_formulir_kota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulir',
            name='kabupaten',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formulir',
            name='prodi2',
            field=models.CharField(blank=True, choices=[('S1 - Pendidikan Dokter', 'S1 - Pendidikan Dokter'), ('D4 - Analis Kesehatan', 'D4 - Analis Kesehatan'), ('S1 - Ilmu Kesehatan Masyarakat', 'S1 - Ilmu Kesehatan Masyarakat'), ('S1 - Gizi', 'S1 - Gizi'), ('S1 - PGSD', 'S1 - PGSD'), ('S1 - PGPAUD', 'S1 - PGPAUD'), ('S1 - Pendidikan Bahasa Inggris', 'S1 - Pendidikan Bahasa Inggris'), ('S1 - Akuntansi', 'S1 - Akuntansi'), ('S1 - Manajemen', 'S1 - Manajemen'), ('S1 - Sistem Informasi', 'S1 - Sistem Informasi'), ('S1 - Keperawatan', 'S1 - Keperawatan'), ('D3 - Keperawatan', 'D3 - Keperawatan'), ('D4 - Bidan', 'D4 - Bidan'), ('D3 - Kebidanan', 'D3 - Kebidanan')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formulir',
            name='prodi3',
            field=models.CharField(blank=True, choices=[('S1 - Pendidikan Dokter', 'S1 - Pendidikan Dokter'), ('D4 - Analis Kesehatan', 'D4 - Analis Kesehatan'), ('S1 - Ilmu Kesehatan Masyarakat', 'S1 - Ilmu Kesehatan Masyarakat'), ('S1 - Gizi', 'S1 - Gizi'), ('S1 - PGSD', 'S1 - PGSD'), ('S1 - PGPAUD', 'S1 - PGPAUD'), ('S1 - Pendidikan Bahasa Inggris', 'S1 - Pendidikan Bahasa Inggris'), ('S1 - Akuntansi', 'S1 - Akuntansi'), ('S1 - Manajemen', 'S1 - Manajemen'), ('S1 - Sistem Informasi', 'S1 - Sistem Informasi'), ('S1 - Keperawatan', 'S1 - Keperawatan'), ('D3 - Keperawatan', 'D3 - Keperawatan'), ('D4 - Bidan', 'D4 - Bidan'), ('D3 - Kebidanan', 'D3 - Kebidanan')], default='', max_length=50, null=True),
        ),
    ]
