# Generated by Django 5.0.6 on 2024-06-02 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0009_alter_formulir_tanggal_lahir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendaftar',
            old_name='nama',
            new_name='nama_lengkap',
        ),
        migrations.RemoveField(
            model_name='pendaftar',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='pendaftar',
            name='umur',
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ijazah', models.FileField(upload_to='uploads/')),
                ('kk', models.FileField(upload_to='uploads/')),
                ('ktp', models.FileField(upload_to='uploads/')),
                ('raport10_1', models.FileField(upload_to='uploads/')),
                ('raport10_2', models.FileField(upload_to='uploads/')),
                ('raport11_1', models.FileField(upload_to='uploads/')),
                ('raport11_2', models.FileField(upload_to='uploads/')),
                ('raport12_1', models.FileField(upload_to='uploads/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
