# Generated by Django 5.0.6 on 2024-06-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0010_rename_nama_pendaftar_nama_lengkap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='nama',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
